### ISSUE TITLE
duplicate libmmcamera_ubifocus_lib.so

### ISSUE THREAD

**Issue by demokritos** [Professor-Berni/proprietary_vendor_sony#1]
Hi,

kitakami-common and suzuran both contain `libmmcamera_ubifocus_lib.so`.

**Comment by demokritos** [comment]
So are libmmcamera_chromaflash_lib.so and libmmcamera_optizoom_lib.so.
libperipheral_client.so is duplicate in kitakami-common. It seems that this library's 32bit and 64bit versions should be located in lib and lib64 directories respectively.
In comparison to TheMuppet's, 32bit version of libsettings.so is missing.

**Comment by Professor-Berni** [comment]
Thank you very much for those hints.
I've fixed it.
libsettings.so is only needed in 64 bit version; libperipheral_client.so too.
